### ISSUE TITLE
可以在adapter中使用吗？

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [liangjingkanji/Channel#10]
使用navigation+fragment hide/show时候需要同步数据

我试了下在adapter中使用，用最简单的发送标签，选中就 sendTag("true")，未选中就 sendTag("false")

然后切换页面，也是在同一个adapter中，填充数据convert中使用

````kotlin
lifecycleOwner.receiveTag("true"){
      setChecked(true,)
}
lifecycleOwner.receiveTag("false"){
      setChecked(false)
}
````

好像不对，我看文档里也没大有介绍标签事件的，`其他基础类型也可以通过字符串表示, 然后使用toInt/toBoolean等函数转为基础类型`这个我也没看明白，应该咋用😂

**Comment by SaltedFish-Extreme** [comment]
@liangjingkanji 麻烦强东哥指点迷津😂

**Comment by liangjingkanji** [comment]
```kotlin
sendTag("2")

receiveTag("2"){
   setChecked(false)
}

// 两个标签使用==为true即会收到事件
```

`其他基础类型也可以通过字符串表示, 然后使用toInt/toBoolean等函数转为基础类型`这句话的意思是你把 `it.toString()` 是不是等于一个数字了. 是不是相当于标签可以直接传数字或者Boolean?

**Comment by liangjingkanji** [comment]
既然很难懂, 这句话我已经从文档中删去了. 本身也作用不大

**Comment by liangjingkanji** [comment]
另外一个Adapter点击事件你通过发送事件实现我认为不可取. Adapter难道不能自己设置点击事件吗? 这样你项目中的事件太多了. 严重滥用

这种类型问题建议群里问吧, 众人拾柴的道理

**Comment by SaltedFish-Extreme** [comment]
@liangjingkanji 😂这样啊，我是想在adapter的item点击事件里同步服务器然后给这个item记录下状态，在切换fragment之后他用的也是这个adapter，我想在那里面获取状态并设置上，要不得走一遍刷新回调才能同步状态😂群里的人太能吹能喷了，早上我发群里一个我刚做的玩安卓app，看上面还是对喷的消息，很久没看群了😂

**Comment by liangjingkanji** [comment]
一个普通点击事件就一个事件. 你这太夸张了

**Comment by SaltedFish-Extreme** [comment]
> 一个普通点击事件就一个事件. 你这太夸张了

😂我也这么想，但是我这没用mvvm架构也没法用livedata同步数据，听网友说只能靠eventbus这种来发消息页面间数据同步，我就想试试这个，写到最后感觉代码变的乱了，就没用上😂

**Comment by SaltedFish-Extreme** [comment]
麻烦老哥的解答了，打扰你了😉

**Comment by liangjingkanji** [comment]
eventbus这种消息机制还是不要滥用, 否则项目很乱

**Comment by SaltedFish-Extreme** [comment]
好的😉
