### ISSUE TITLE
根据发送事件的状态来接收进行不同的操作怎么做

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [liangjingkanji/Channel#11]
比如收藏，取消收藏返回上个页面应该删除那条数据，收藏应该不变
我现在不知道应该使用`sendEvent(data, "tag_unCollect")`还是使用`sendEvent(data, true.toString()/false.toString())`，我看发送事件不能为null
接收的时候不知道应该怎样判断传递的tag是true还是false，不知道我用的对不对😂

**Comment by liangjingkanji** [comment]
**如果事件存在标签, 则事件类型相同标签相等才能收到事件**

data应该是只针对取消收藏的对象吧? 那没必要用什么tag

```kotlin
val data:CollectModel

// 发送
sendEvent(data)


receiveEvent{
   // 接受取消收藏事件
}
```

标签是用来区分事件的, 不是用来让你传递数据的. 如果标签传递数据, 那Event是干什么的

如果你一个事件有多个状态, 就给Event对象加个字段来表示状态

**Comment by liangjingkanji** [comment]
如果不知道函数怎么用建议你点开源文件, 看下函数列表, 看下函数声明.

**Comment by SaltedFish-Extreme** [comment]
嗯，我是想取消收藏的时候发送，把model传过去，如果取消了之后又收藏，就不传过去model了😂现在我不知道怎样能不传递过去，接收的时候也不知道该这么判断😂

**Comment by liangjingkanji** [comment]
取消的时候你也传过去不行吗? 如果不行你就再定义一个事件或者创建空对象

> 如果取消了之后又收藏，就不传过去model了😂现在我不知道怎样能不传递过去，接收的时候也不知道该这么判断😂

关于你这个问题我也不知道

**Comment by SaltedFish-Extreme** [comment]
😂目前来看好像我取消之后再收藏，返回上个页面还是把数据传递过去了，我试试给model加个字段吧😂

**Comment by SaltedFish-Extreme** [comment]
我把发送事件放在页面销毁之前了，这样就不用判断发送收藏还是取消了😂在最后判断取消收藏就发送事件就好了，还是技术太菜了😂

**Comment by liangjingkanji** [comment]
实现方式都行, 代码不是复制. 有思路就行

**Comment by SaltedFish-Extreme** [comment]
嗯😂
