### ISSUE TITLE
有没有办法接收到一个事件后，拦截后续接收此事件

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [liangjingkanji/Channel#12]
我发现销毁当前页面后发送事件，返回的页面收到事件同步数据，同时这个页面的其余fragment也会接收事件，重复同步了😂

**Comment by liangjingkanji** [comment]
没有, 每个接受者互相独立的

你可以自己给Fragment加一个字段用于判断是否已经处理过事件

**Comment by SaltedFish-Extreme** [comment]
好吧，那应该是我写法有问题，我改改看看😂
