### ISSUE TITLE
如果一个界面有多个tag，并且每个tag要处理的不一样怎么整

### ISSUE THREAD

**Issue by JasonYinH** [liangjingkanji/Channel#13]
比如A,B,C界面：
B界面作为接收A,C发送的消息。
     A发送tagA告诉B界面,打开相册
     C发送tagC告诉B界面,打开相机；
这样，难道要写两个receiveTag吗，不能通过一个receiveTag在里面判断吗

![image](https://user-images.githubusercontent.com/40187930/167247496-ab308b0e-8894-4ea4-9adf-f0f4101c0741.png)

**Comment by liangjingkanji** [comment]
你觉得写两个receiveTag和判断你觉得两者谁简单? 我个人认为写两个更简单

但是你相机拍摄和选择相册都属于通用逻辑, 所以你可以为receiveTag写两个tag参数(receiveTag可以接受多个tag参数)
