### ISSUE TITLE
重复收到事件

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [liangjingkanji/Channel#14]
我在添加用户页面发送消息，关闭掉之后在上个页面接收消息显示添加后的用户，每次成功添加发送消息后，上个页面添加的用户都会重复多，多次收到消息就多次重复添加那一个用户到adapter数据里面

**Comment by liangjingkanji** [comment]
请fork仓库在demo复现

**Comment by SaltedFish-Extreme** [comment]
> 请fork仓库在demo复现

在你demo里没问题，后来看是写错生命周期了，我之前是在onResume里执行的，现在在onViewCreated里执行就没问题了
