### ISSUE TITLE
想要在主页面全局监听一个变量，请问有方法吗？

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [liangjingkanji/Channel#16]
我打算和Serialize一起用，但是不知道该怎么监听这个😂

**Comment by liangjingkanji** [comment]
Serialize支持创建`LiveData`, 你用这个监听(LiveData可以选择使用生命周期或者不使用)

**Comment by SaltedFish-Extreme** [comment]
> Serialize支持创建`LiveData`, 你用这个监听(LiveData可以选择使用生命周期或者不使用)

对，我是看到有个serialLiveData，但是不知道该怎么用😂我看只能设置成val，不知道该咋使用😂

**Comment by SaltedFish-Extreme** [comment]
刚才看了看序列化里的demo，找到方法了，还是我不会用livedata😂打扰老哥了
