### ISSUE TITLE
能否搞个插件，可以跳转到对应的监听事件位置

### ISSUE THREAD

**Issue by stars-one** [liangjingkanji/Channel#20]
像eventbus，插件市场有个插件，可以跳转到发送事件或监听事件的地方，可以很方便代码阅读，不知道作者或其他小伙伴有计划？

**Comment by liangjingkanji** [comment]
如果是标签事件, 遵守命名规范即可, 比如tag都以`"登录成功_事件"`, 这个时候你全局搜索这个标签即可

如果是event, 那直接使用IDE的`find_usage`即可

根本用不上插件嘛... 善用搜索功能
