### ISSUE TITLE
请教一下这个问题

### ISSUE THREAD

**Issue by TangStudio** [liangjingkanji/Channel#21]
activity里边发送给这个activity里边的fragment消息，接收的函数写在fragment里的哪个生命周期合适呢？我试了一下都接收不了。。。

**Comment by liangjingkanji** [comment]
我首先认为你不应该这么做

fragment和activity本身就可以互相获取对方引用, 你不要滥用事件分发框架

**Comment by TangStudio** [comment]
感谢
