### ISSUE TITLE
livedata 接收数据

### ISSUE THREAD

**Issue by EdwinSmartBoy** [liangjingkanji/Channel#24]
请问一下，有什么方式实现只在页面活跃的时候才接收数据，不活跃的时候不处理，直接丢弃

**Comment by liangjingkanji** [comment]
接受到事件时判断下, 如果当前页面不活跃直接return

**Comment by EdwinSmartBoy** [comment]
好的，一开始我以为可以像flow一样，到达指定生命周期不监听这种，恢复后又监听之类的
