### ISSUE TITLE
很棒的一个Channel

### ISSUE THREAD

**Issue by carozhu** [liangjingkanji/Channel#4]
很棒的一个Channel

**Comment by liangjingkanji** [comment]
简单且强大

**Comment by xuexirong** [comment]
@liangjingkanji 我们用的navigation+fragment 单页面应用  用eventbus 接收数据刷新页面，由于fragment用的replace替换，有时候view为null，之前都是自己写个event+livedata 来刷新页面。现在发现大佬这个非常合适，完美的解决了我项目的问题，希望大佬一直维护下去

**Comment by liangjingkanji** [comment]
@xuexirong 会一直维护的

**Comment by xuexirong** [comment]
东哥&nbsp; 遇到个技术问题&nbsp; 想你请教 方便加QQ么&nbsp; &nbsp;不知道咋直接联系你&nbsp; &nbsp;我们app做了个闹钟功能&nbsp; 但是在华为手机息屏后&nbsp; 计时器会暂停&nbsp; 有时候app也会被杀死&nbsp; &nbsp;






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liangjingkanji/Channel"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月16日(星期天) 下午3:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [liangjingkanji/Channel] 很棒的一个Channel (#4)





 
@xuexirong 一直有在维护
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by liangjingkanji** [comment]
@xuexirong 技术问题你可以加群问, 我也不是什么技术都会

**Comment by xuexirong** [comment]
好的，谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月13日(周一) 下午3:31
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [liangjingkanji/Channel] 很棒的一个Channel (#4)




 
@xuexirong 技术问题你可以加群问, 我也不是什么技术都会
